const activities = [
  {
    id: 1,
    type: 'read',
    timeCat: '15',
    name: 'read activity',
    timeEst: '13 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 2,
    type: 'read',
    timeCat: '30',
    name: 'read activity',
    timeEst: '26 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 3,
    type: 'read',
    timeCat: '45',
    name: 'read activity',
    timeEst: '39 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 4,
    type: 'read',
    timeCat: 'hour',
    name: 'read activity',
    timeEst: '55 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 5,
    type: 'watch',
    timeCat: '15',
    name: 'watch activity',
    timeEst: '13 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 6,
    type: 'watch',
    timeCat: '30',
    name: 'watch activity',
    timeEst: '26 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 7,
    type: 'watch',
    timeCat: '45',
    name: 'watch activity',
    timeEst: '39 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 8,
    type: 'watch',
    timeCat: 'hour',
    name: 'watch activity',
    timeEst: '59 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 9,
    type: 'learn',
    timeCat: '15',
    name: 'learn activity',
    timeEst: '12 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 10,
    type: 'learn',
    timeCat: '30',
    name: 'learn activity',
    timeEst: '22 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 11,
    type: 'learn',
    timeCat: '45',
    name: 'learn activity',
    timeEst: '41 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 12,
    type: 'learn',
    timeCat: 'hour',
    name: 'learn activity',
    timeEst: '55 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 13,
    type: 'do',
    timeCat: '15',
    name: 'do activity',
    timeEst: '12 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 14,
    type: 'do',
    timeCat: '30',
    name: 'do activity',
    timeEst: '26 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 15,
    type: 'do',
    timeCat: '45',
    name: 'do activity',
    timeEst: '39 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 16,
    type: 'do',
    timeCat: 'hour',
    name: 'do activity',
    timeEst: '49 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 17,
    type: 'read',
    timeCat: '15',
    name: 'read activity',
    timeEst: '13 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 18,
    type: 'read',
    timeCat: '30',
    name: 'read activity',
    timeEst: '26 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 19,
    type: 'read',
    timeCat: '45',
    name: 'read activity',
    timeEst: '39 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 20,
    type: 'read',
    timeCat: 'hour',
    name: 'read activity',
    timeEst: '55 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 21,
    type: 'watch',
    timeCat: '15',
    name: 'watch activity',
    timeEst: '13 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 22,
    type: 'watch',
    timeCat: '30',
    name: 'watch activity',
    timeEst: '26 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 23,
    type: 'watch',
    timeCat: '45',
    name: 'watch activity',
    timeEst: '39 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 24,
    type: 'watch',
    timeCat: 'hour',
    name: 'watch activity',
    timeEst: '59 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 25,
    type: 'learn',
    timeCat: '15',
    name: 'learn activity',
    timeEst: '12 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 26,
    type: 'learn',
    timeCat: '30',
    name: 'learn activity',
    timeEst: '22 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 27,
    type: 'learn',
    timeCat: '45',
    name: 'learn activity',
    timeEst: '41 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 28,
    type: 'learn',
    timeCat: 'hour',
    name: 'learn activity',
    timeEst: '55 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 29,
    type: 'do',
    timeCat: '15',
    name: 'do activity',
    timeEst: '12 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 30,
    type: 'do',
    timeCat: '30',
    name: 'do activity',
    timeEst: '26 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 31,
    type: 'do',
    timeCat: '45',
    name: 'do activity',
    timeEst: '39 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 32,
    type: 'do',
    timeCat: 'hour',
    name: 'do activity',
    timeEst: '49 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
]

module.exports = { activities }
