const activities = [
  {
    id: 1,
    type: 'read',
    timeCat: '30',
    name: 'The Lottery',
    timeEst: '25 minutes',
    description:
      'Classic short story from 1948 by Shirley Jackson. Kind of disturbing...',
    link: 'https://www.newyorker.com/magazine/1948/06/26/the-lottery',
    score: 10,
  },
  {
    id: 2,
    type: 'watch',
    timeCat: '15',
    name: 'Meshes of the Afternoon',
    timeEst: '14 minutes',
    description: 'Classic short film from 1943 by Maya Deren. A bit surreal.',
    link: 'https://####//',
    score: 8,
  },
  {
    id: 3,
    type: 'watch',
    timeCat: '15',
    name: 'Born to be Mild',
    timeEst: '15 minutes',
    description: `Documentary about The Dull Men's Club from 2014. Ironically, it's quite interesting.`,
    link: 'https://vimeo.com/183524061',
    score: 8,
  },
  {
    id: 4,
    type: 'watch',
    timeCat: '15',
    name: 'Wellington Wharves & Eastern Suburbs',
    timeEst: '9 minutes',
    description: 'Archive footage of Wellington from the 1950s.',
    link: 'https://www.youtube.com/watch?v=YWPeZ2RUk7I',
    score: 7,
  },
  {
    id: 5,
    type: 'read',
    timeCat: '30',
    name: `Oh, Whistle, and I'll Come to You My Lad `,
    timeEst: '25 minutes',
    description: 'Creepy old-school ghost story by M.R. James (from 1904)',
    link: 'https://en.wikisource.org/wiki/Ghost_Stories_of_an_Antiquary/%27Oh,_Whistle,_and_I%27ll_Come_to_You_My_Lad%27',
    score: 9,
  },
  {
    id: 6,
    type: 'read',
    timeCat: '30',
    name: 'JavaScript Wikipedia Page',
    timeEst: '28 minutes',
    description: 'Read all about the history of JS!',
    link: 'https://en.wikipedia.org/wiki/JavaScript',
    score: 10,
  },
]

module.exports = { activities }
