const activities = [
  {
    id: 1,
    type: 'read',
    timeCat: '15',
    name: 'Pineapple',
    timeEst: '13 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 2,
    type: 'read',
    timeCat: '30',
    name: 'Goat',
    timeEst: '26 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 3,
    type: 'read',
    timeCat: '45',
    name: 'Yellow',
    timeEst: '39 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 4,
    type: 'read',
    timeCat: 'hour',
    name: 'Monkey',
    timeEst: '55 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 5,
    type: 'watch',
    timeCat: '15',
    name: 'Bed',
    timeEst: '13 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 6,
    type: 'watch',
    timeCat: '30',
    name: 'Blue',
    timeEst: '26 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 7,
    type: 'watch',
    timeCat: '45',
    name: 'Orange',
    timeEst: '39 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 8,
    type: 'watch',
    timeCat: 'hour',
    name: 'Zoo',
    timeEst: '59 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 9,
    type: 'learn',
    timeCat: '15',
    name: 'Nigel',
    timeEst: '12 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 10,
    type: 'learn',
    timeCat: '30',
    name: 'Pillow',
    timeEst: '22 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 11,
    type: 'learn',
    timeCat: '45',
    name: 'Soapbox',
    timeEst: '41 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 12,
    type: 'learn',
    timeCat: 'hour',
    name: 'Window',
    timeEst: '55 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 13,
    type: 'do',
    timeCat: '15',
    name: 'Drumroll',
    timeEst: '12 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 14,
    type: 'do',
    timeCat: '30',
    name: 'This that and the other',
    timeEst: '26 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 15,
    type: 'do',
    timeCat: '45',
    name: 'Great Expectations',
    timeEst: '39 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 16,
    type: 'do',
    timeCat: 'hour',
    name: 'The Pickwick Papers',
    timeEst: '49 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 17,
    type: 'read',
    timeCat: '15',
    name: 'Catcher in the Rye',
    timeEst: '13 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 18,
    type: 'read',
    timeCat: '30',
    name: 'Gravity Rainbow',
    timeEst: '26 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 19,
    type: 'read',
    timeCat: '45',
    name: 'Watership Down',
    timeEst: '39 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 20,
    type: 'read',
    timeCat: 'hour',
    name: 'Shardik',
    timeEst: '55 minutes',
    description: 'Read read read',
    link: 'link link link',
    score: 10,
  },
  {
    id: 21,
    type: 'watch',
    timeCat: '15',
    name: 'Wolf!',
    timeEst: '13 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 22,
    type: 'watch',
    timeCat: '30',
    name: 'Three Little Pigs',
    timeEst: '26 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 23,
    type: 'watch',
    timeCat: '45',
    name: 'Lampshade',
    timeEst: '39 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 24,
    type: 'watch',
    timeCat: 'hour',
    name: 'Nightingales',
    timeEst: '59 minutes',
    description: 'watch watch watch',
    link: 'link link link',
    score: 10,
  },
  {
    id: 25,
    type: 'learn',
    timeCat: '15',
    name: 'Noisy',
    timeEst: '12 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 26,
    type: 'learn',
    timeCat: '30',
    name: 'Loud Music',
    timeEst: '22 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 27,
    type: 'learn',
    timeCat: '45',
    name: 'What!',
    timeEst: '41 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 28,
    type: 'learn',
    timeCat: 'hour',
    name: 'Wallpaper',
    timeEst: '55 minutes',
    description: 'learn learn learn',
    link: 'link link link',
    score: 10,
  },
  {
    id: 29,
    type: 'do',
    timeCat: '15',
    name: 'Paint Dry',
    timeEst: '12 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 30,
    type: 'do',
    timeCat: '30',
    name: 'Perfume',
    timeEst: '26 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 31,
    type: 'do',
    timeCat: '45',
    name: 'Doorway',
    timeEst: '39 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
  {
    id: 32,
    type: 'do',
    timeCat: 'hour',
    name: 'Free Association',
    timeEst: '49 minutes',
    description: 'do do do',
    link: 'link link link',
    score: 10,
  },
]

module.exports = { activities }
